---
- name   : Install default Atop WebServers
  hosts  : test33
  become : yes
  
  tasks:
    - name: Install Atop WebServers
      ansible.builtin.apt:
        name: atop
        state: present 

    - name: aa
      service:
        name: atop 
        state: started  
        enabled: yes
 

